[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "jinja2>=3.1.6",
    "pandas>=2.2.3",
    "python-multipart>=0.0.20",
    "streamlit>=1.45.1",
    "uvicorn>=0.34.2",
]
